### ISSUE TITLE
Using badges on Web App

### ISSUE THREAD

**Issue by marinaaraujo97** [YaDaniil/flutter_badges#116]
Hello there!

I have a flutter app that runs both on Android and Web platforms.

On Android I getthe desired look as you can see below: 

![Screenshot_20230721_153922](https://github.com/yako-dev/flutter_badges/assets/71660311/1c469389-5dc6-43a3-a2af-a702cb152445)

But on Web I get this error:

![Captura de ecrã 2023-07-21 154244](https://github.com/yako-dev/flutter_badges/assets/71660311/223386b3-facc-417b-9cc4-5c5dae27e5e1)

Can someone please help?

**Comment by M-ixai-L** [comment]
@marinaaraujo97 Sorry for the long delay, is this still relevant or can we close the issue?

**Comment by yadaniyil** [comment]
@marinaaraujo97 please make sure you check the platform in your code with kIsWeb (https://api.flutter.dev/flutter/foundation/kIsWeb-constant.html) before checking it with Platform.operatingSystem. Most of the times this is the solution to your issue.
